config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Stocktake.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Stocktake Entity
 *
 * @property int $id
 * @property int $user_store_id
 * @property int $product_id
 * @property float $current_stock_qty
 * @property float $suggested_order_qty
 * @property float $total_req_qty
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 *
 * @property \App\Model\Entity\UserStore $user_store
 * @property \App\Model\Entity\Product $product
 */
class Stocktake extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Entity/UserStore.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * UserStore Entity
 *
 * @property int $id
 * @property int $user_id
 * @property int $store_id
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 *
 * @property \App\Model\Entity\User $user
 * @property \App\Model\Entity\Store $store
 * @property \App\Model\Entity\PriceCheck[] $price_checks
 * @property \App\Model\Entity\Stocktake[] $stocktakes
 * @property \App\Model\Entity\UserStoreOrder[] $user_store_orders
 * @property \App\Model\Entity\UserStoreSupplier[] $user_store_suppliers
 */
class UserStore extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
	
	// virtual properties to get the UserStore User_name & Store_name
	protected function _getUserStoreNames()
	{
		// this return below returns the user_id and store_id of the table that's it's connected to.
		//return $this->user_id . ' - ' . $this->store_id;
		return $this->user->user_name . ' - ' . $this->store->store_name;
		//debug($this); die;
		
	}
}

src/Model/Table/StocktakesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Stocktakes Model
 *
 * @property \Cake\ORM\Association\BelongsTo $UserStores
 * @property \Cake\ORM\Association\BelongsTo $Products
 *
 * @method \App\Model\Entity\Stocktake get($primaryKey, $options = [])
 * @method \App\Model\Entity\Stocktake newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Stocktake[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Stocktake|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Stocktake patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Stocktake[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Stocktake findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class StocktakesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('stocktakes');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('UserStores', [
            'foreignKey' => 'user_store_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Products', [
            'foreignKey' => 'product_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->decimal('current_stock_qty')
            ->requirePresence('current_stock_qty', 'create')
            ->notEmpty('current_stock_qty');

        $validator
            ->decimal('suggested_order_qty')
            ->requirePresence('suggested_order_qty', 'create')
            ->notEmpty('suggested_order_qty');

        $validator
            ->decimal('total_req_qty')
            ->requirePresence('total_req_qty', 'create')
            ->notEmpty('total_req_qty');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_store_id'], 'UserStores'));
        $rules->add($rules->existsIn(['product_id'], 'Products'));

        return $rules;
    }
}

src/Controller/StocktakesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Stocktakes Controller
 *
 * @property \App\Model\Table\StocktakesTable $Stocktakes
 */
class StocktakesController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['UserStores' => function($query)
                          {
                              return $query->find('userStoreName');
                          }, 
                          'Products']
        ];
        $stocktakes = $this->paginate($this->Stocktakes); //`$this->paginate()` can take a Table instance *or* a query
        $this->set(compact('stocktakes'));
        $this->set('_serialize', ['stocktakes']);
    }

    /**
     * View method
     *
     * @param string|null $id Stocktake id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $stocktake = $this->Stocktakes->get($id, [
            'contain' => ['UserStores', 'Products']
        ]);

        $this->set('stocktake', $stocktake);
        $this->set('_serialize', ['stocktake']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $stocktake = $this->Stocktakes->newEntity();
        if ($this->request->is('post')) {
            $stocktake = $this->Stocktakes->patchEntity($stocktake, $this->request->getData());
            if ($this->Stocktakes->save($stocktake)) {
                $this->Flash->success(__('The stocktake has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The stocktake could not be saved. Please, try again.'));
        }
        $userStores = $this->Stocktakes->UserStores->find('list')->contain(
																	[
																		'Users' => ['fields' => ['user_name']],
																		'Stores' => ['fields' => ['store_name']]
																	]);
        $products = $this->Stocktakes->Products->find('list');
        $this->set(compact('stocktake', 'userStores', 'products'));
        $this->set('_serialize', ['stocktake']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Stocktake id.
     * @return \Cake\Network\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $stocktake = $this->Stocktakes->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $stocktake = $this->Stocktakes->patchEntity($stocktake, $this->request->getData());
            if ($this->Stocktakes->save($stocktake)) {
                $this->Flash->success(__('The stocktake has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The stocktake could not be saved. Please, try again.'));
        }
         $userStores = $this->Stocktakes->UserStores->find('list')->contain(
																	[
																		'Users' => ['fields' => ['user_name']],
																		'Stores' => ['fields' => ['store_name']]
																	]);
        $products = $this->Stocktakes->Products->find('list');
        $this->set(compact('stocktake', 'userStores', 'products'));
        $this->set('_serialize', ['stocktake']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Stocktake id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $stocktake = $this->Stocktakes->get($id);
        if ($this->Stocktakes->delete($stocktake)) {
            $this->Flash->success(__('The stocktake has been deleted.'));
        } else {
            $this->Flash->error(__('The stocktake could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Stocktakes/add.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Stocktakes'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List User Stores'), ['controller' => 'UserStores', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New User Store'), ['controller' => 'UserStores', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Products'), ['controller' => 'Products', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Product'), ['controller' => 'Products', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="stocktakes form large-9 medium-8 columns content">
    <?= $this->Form->create($stocktake) ?>
    <fieldset>
        <legend><?= __('Add Stocktake') ?></legend>
        <?php
            echo $this->Form->control('user_store_id', ['options' => $userStores]);
            echo $this->Form->control('product_id', ['type'=>'select','multiple'=>true,'options' => $products]);
            echo $this->Form->control('current_stock_qty');
            echo $this->Form->control('suggested_order_qty');
            echo $this->Form->control('total_req_qty');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Stocktakes/edit.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $stocktake->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $stocktake->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Stocktakes'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List User Stores'), ['controller' => 'UserStores', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New User Store'), ['controller' => 'UserStores', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Products'), ['controller' => 'Products', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Product'), ['controller' => 'Products', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="stocktakes form large-9 medium-8 columns content">
    <?= $this->Form->create($stocktake) ?>
    <fieldset>
        <legend><?= __('Edit Stocktake') ?></legend>
        <?php
            echo $this->Form->control('user_store_id', ['options' => $userStores]);
            echo $this->Form->control('product_id', ['options' => $products]);
            echo $this->Form->control('current_stock_qty');
            echo $this->Form->control('suggested_order_qty');
            echo $this->Form->control('total_req_qty');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Stocktakes/index.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<nav class="" id="otherActionNav">
    <ul class="nav nav-pills">
		<h4>Other Navigations:-</h4>
        <li><?= $this->Html->link(__('New Stocktake'), ['action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List User Stores'), ['controller' => 'UserStores', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New User Store'), ['controller' => 'UserStores', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Products'), ['controller' => 'Products', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Product'), ['controller' => 'Products', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div id="indexContent" class="">
    <h3><?= __('Stocktakes') ?></h3>
    <table class="table" cellpadding="0" cellspacing="0">>
        <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('user_store_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('product_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('current_stock_qty') ?></th>
                <th scope="col"><?= $this->Paginator->sort('suggested_order_qty') ?></th>
                <th scope="col"><?= $this->Paginator->sort('total_req_qty') ?></th>
                <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                <th scope="col"><?= $this->Paginator->sort('modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($stocktakes as $stocktake): ?>
            <tr>
                <td><?= $this->Number->format($stocktake->id) ?></td>
                <td><?= $stocktake->has('user_store') ? $this->Html->link($stocktake->user_store->user_store_names, ['controller' => 'UserStores', 'action' => 'view', $stocktake->user_store->id]) : '' ?></td>
                <td><?= $stocktake->has('product') ? $this->Html->link($stocktake->product->product_name, ['controller' => 'Products', 'action' => 'view', $stocktake->product->id]) : '' ?></td>
                <td><?= $this->Number->format($stocktake->current_stock_qty) ?></td>
                <td><?= $this->Number->format($stocktake->suggested_order_qty) ?></td>
                <td><?= $this->Number->format($stocktake->total_req_qty) ?></td>
                <td><?= h($stocktake->created) ?></td>
                <td><?= h($stocktake->modified) ?></td>
                <td class="actions">                    
                    <?php echo $this->Html->link('<span class = "glyphicon glyphicon-eye-open"></span>',['action' => 'view', $stocktake->id],['class' => 'btn btn-primary', 'role' => 'button', 'escape' => false]);?>
					<?php echo $this->Html->link('<span class = "glyphicon glyphicon-pencil"></span>',['action' => 'edit', $stocktake->id],['class' => 'btn btn-success', 'role' => 'button', 'escape' => false]);?>
					<?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $stocktake->id], ['confirm' => __('Are you sure you want to delete # {0}?', $stocktake->id), 'class' => 'btn btn-danger']) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>

src/Template/Stocktakes/view.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Stocktake'), ['action' => 'edit', $stocktake->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Stocktake'), ['action' => 'delete', $stocktake->id], ['confirm' => __('Are you sure you want to delete # {0}?', $stocktake->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Stocktakes'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Stocktake'), ['action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List User Stores'), ['controller' => 'UserStores', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New User Store'), ['controller' => 'UserStores', 'action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Products'), ['controller' => 'Products', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Product'), ['controller' => 'Products', 'action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="stocktakes view large-9 medium-8 columns content">
    <h3><?= h($stocktake->id) ?></h3>
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('User Store') ?></th>
            <td><?= $stocktake->has('user_store') ? $this->Html->link($stocktake->user_store->id, ['controller' => 'UserStores', 'action' => 'view', $stocktake->user_store->id]) : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Product') ?></th>
            <td><?= $stocktake->has('product') ? $this->Html->link($stocktake->product->id, ['controller' => 'Products', 'action' => 'view', $stocktake->product->id]) : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($stocktake->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Current Stock Qty') ?></th>
            <td><?= $this->Number->format($stocktake->current_stock_qty) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Suggested Order Qty') ?></th>
            <td><?= $this->Number->format($stocktake->suggested_order_qty) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Total Req Qty') ?></th>
            <td><?= $this->Number->format($stocktake->total_req_qty) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($stocktake->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($stocktake->modified) ?></td>
        </tr>
    </table>
</div>